version: '3.8'

services:
  nginx :
    container_name : proxies
    build:
      context : .
      dockerfile: nginx/Dockerfile
    ports:
      - 8080:80
      - 8081:81
      - 8082:82
    networks : 
      - internal
  app :
    container_name: app
    build : 
      context: .
      dockerfile: Dockerfile
    networks:
      - internal
  api-01 :
    container_name: api-02
    image : mrpachara/api-01-fpm:latest
    environment:
      - ACCESS_TOKEN=spicy_token
    networks:
      - internal 
  api-02 :
    container_name: api-02
    image : ryoneme2/api-02:lastest
    environment:
      - PORT=8008
      - ACCESS_TOKEN=spicy_token
    networks:
      - internal 

networks:
  internal :
    driver: bridge

